name: CMake

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  push:
    branches: [ master, alpha ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installation
      run: |
        echo "Install dependencies of ZAF"
        cd ${{github.workspace}}/../
        git clone --depth 1 https://github.com/zzxx-husky/inst_scripts
        ./inst_scripts/install_zaf.sh --deps-only
        cd ${{github.workspace}}

        echo "Install Clang"
        sudo apt install clang
        clang --version
        clang++ --version

        echo "Install Valgrind"
        sudo apt install -y valgrind

    - name: Configure CMake
      # Configure CMake in a 'release' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        . ${HOME}/.bashrc
        echo ${ZMQ_ROOT}
        echo ${GTEST_ROOT}
        echo ${GLOG_ROOT}
        echo ${PHMAP_ROOT}
        cmake -S . -B ${{github.workspace}}/release -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/release

    - name: Test
      working-directory: ${{github.workspace}}/release
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: timeout 10 ./tests/Tests

    - name: Examples
      working-directory: ${{github.workspace}}/release
      run: |
        echo "Run HelloWorld"
        ./examples/HelloWorld
        echo "Run HelloWorldX"
        ./examples/HelloWorldX
        echo "Run HelloWorldNetwork"
        ./examples/HelloWorldNetwork
        echo "Run HelloWorldByActorEngine"
        ./examples/HelloWorldByActorEngine
        echo "Run Shuffle"
        ./examples/Shuffle
        echo "Run ShuffleX"
        ./examples/ShuffleX
        echo "Run LoadRebalance"
        ./examples/LoadRebalance
        echo "RUn ActorDelivery"
        ./examples/ActorDelivery

    - name: BuildMini
      run: |
        cmake -B ${{github.workspace}}/release_mini -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TEST=false -DENABLE_PHMAP=false
        cd ${{github.workspace}}/release_mini
        make all -j4
        echo "Run HelloWorld"
        ./examples/HelloWorld
        echo "Run HelloWorldNetwork"
        ./examples/HelloWorldNetwork
        echo "Run HelloWorldByActorEngine"
        ./examples/HelloWorldByActorEngine

    - name: Valgrind
      working-directory: ${{github.workspace}}/release
      run: |
        valgrind ./examples/HelloWorld
        valgrind ./examples/HelloWorldX
        valgrind ./examples/HelloWorldByActorEngine
        valgrind ./examples/HelloWorldNetwork

    - name: Compile with Clang
      run: |
        cmake -B ${{github.workspace}}/release_clang -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cd ${{github.workspace}}/release_clang
        make all -j4
        echo "Run HelloWorld"
        ./examples/HelloWorld
        echo "Run HelloWorldNetwork"
        ./examples/HelloWorldNetwork
        echo "Run HelloWorldByActorEngine"
        ./examples/HelloWorldByActorEngine
      env:
        CC: clang
        CXX: clang++
